USE HowKteam
GO

SELECT * FROM dbo.GIAOVIEN , dbo.BOMON
WHERE dbo.BOMON.MABM = dbo.GIAOVIEN.MABM

SELECT * FROM dbo.GIAOVIEN FULL OUTER JOIN dbo.BOMON
ON BOMON.MABM = GIAOVIEN.MABM

SELECT * FROM dbo.BOMON FULL OUTER JOIN dbo.GIAOVIEN
ON   GIAOVIEN.MABM= BOMON.MABM