-- CREATE DATABASE minhphuc
--Tạo 1 database bằng code
--chỉ tạo được 1 tên duy nhất
--thực thi lệnh có 2 cách: nhấn f5. hoặc Execute
--Nếu bôi đen dòng nào thì thực thi dòng đó
--Nếu không bôi đen thì thực thi cả file